### ISSUE TITLE
Not working as of 11.3 

### ISSUE THREAD

**Issue by Senuaa** [antD97/SDPS#2]
on any version the follow issue appears upon opening the program:

java.lang.IndexOutOfBoundsException: Index 1 out of bounds for length 1
	at java.base/jdk.internal.util.Preconditions.outOfBounds(Unknown Source)
	at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Unknown Source)
	at java.base/jdk.internal.util.Preconditions.checkIndex(Unknown Source)
	at java.base/java.util.Objects.checkIndex(Unknown Source)
	at java.base/java.util.ArrayList.get(Unknown Source)
	at sdps.DamageTracker.run(DamageTracker.kt:77)
	at sdps.MainKt.main(Main.kt:74)
	at sdps.MainKt.main(Main.kt)

**Comment by antD97** [comment]
Sorry for the late response. Everything is working fine on my end. Is it still happening for you?

If you go into your `Documents/My Games/Smite/BattleGame/Logs` folder and send me all the `.log` files in a zip file, I can try to see what happened and possibly release a fix. If you just want it working again, you can move/delete all those `.log` files and it should be okay again.

**Comment by Senuaa** [comment]
I appreciate you getting back to me, I was able to fix it by clicking the
refresh button next to the in game name field. I know my friend had a
similar issue as me but I am unsure how he got it resolved. I will let you
know if I have any more problems.
